global:
  scrape_interval:     2s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "app"
    static_configs:
       - targets: [ "0.0.0.0:2112" ]  # Этот адрес почему-то не работает
#       - targets: [ "host.docker.internal:2112" ]  # Этот адрес почему-то не работает
#      - targets: [ "172.17.0.1:2112" ]  # Этот адрес почему-то не работает
#      - targets: [ "localhost:2112" ]      
 
